# Generated by Django 5.2.6 on 2025-10-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='결제 승인 시간'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_type',
            field=models.CharField(default='N/A', max_length=50, verbose_name='결제 수단'),
        ),
    ]
