# Generated by Django 5.2.6 on 2025-10-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item_name',
            field=models.CharField(default='default_item', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_type',
            field=models.CharField(default='default_method', max_length=100),
        ),
    ]
