# Generated by Django 5.2.6 on 2025-10-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Payment", "0003_alter_payment_options_payment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="item_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method_type",
            field=models.CharField(default="CARD", max_length=20),
        ),
    ]
