# Generated by Django 5.2.6 on 2025-09-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_payment_options_payment_aid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_info',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tax_free_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vat_amount',
        ),
    ]
