# Generated by Django 5.2.4 on 2025-09-20 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='경매 제목')),
                ('description', models.TextField(verbose_name='경매 설명')),
                ('starting_price', models.PositiveIntegerField(verbose_name='시작가')),
                ('current_price', models.PositiveIntegerField(default=0, verbose_name='현재가')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='auction_images/', verbose_name='이미지 파일')),
                ('status', models.CharField(choices=[('active', '진행중'), ('ended', '종료'), ('cancelled', '취소')], default='active', max_length=20, verbose_name='경매 상태')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_sold', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_won', to=settings.AUTH_USER_MODEL, verbose_name='낙찰자')),
            ],
            options={
                'verbose_name': '경매',
                'verbose_name_plural': '경매들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='입찰가')),
                ('bid_time', models.DateTimeField(auto_now_add=True, verbose_name='입찰 시간')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Auction.auction', verbose_name='경매')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='입찰자')),
            ],
            options={
                'verbose_name': '입찰',
                'verbose_name_plural': '입찰들',
                'ordering': ['-bid_time'],
            },
        ),
    ]
